language: java

cache:
   directories:
      - "$HOME/.m2"

script:
   - ./mvnw test -Dmaven.test.failure.ignore
   - grep -q "The step \"I wait 1 hour\" is undefined." target/surefire-reports/io.cucumber.skeleton.RunCucumberTest.txt || ( echo "mvn test didn't fail as expected" && false )
